
[functions.start-assistant-run]
enabled = true
verify_jwt = true
import_map = "./functions/start-assistant-run/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/start-assistant-run/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/start-assistant-run/*.html" ]

[functions.hello_world]
enabled = true
verify_jwt = true
import_map = "./functions/hello_world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello_world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello_world/*.html" ]

[functions.StoryArcsAssistant]
enabled = true
verify_jwt = true
import_map = "./functions/StoryArcsAssistant/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/StoryArcsAssistant/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/StoryArcsAssistant/*.html" ]
